[project]
name = "slo-search"
version = "0.1.0"
dependencies = [
    "fastapi",
    "fastmcp",
    "mcp",
    "openai",
    "pydal",
    "psycopg2-binary",
    "numpy",
    "requests",
    "tqdm",
    "uvicorn",
    "edwh",
]
